import { Answers, isFieldActive } from '../voice/conversation';
import { FormSchema } from '../schema/types';

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// A plain field:value list rather than a visual replica of the original form (PLAN.md §7 flags
// that as a nice-to-have, not required) — simplest reliable path for a print-ready PDF.
export function generateFormHtml(schema: FormSchema, answers: Answers): string {
  const rows = schema.fields
    .filter((field) => answers[field.id] !== undefined && isFieldActive(field, answers))
    .map(
      (field) => `
        <tr>
          <td class="label">${escapeHtml(field.label)}</td>
          <td class="value">${escapeHtml(answers[field.id])}</td>
        </tr>`
    )
    .join('');

  const printedOn = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });

  return `
    <html>
      <head>
        <meta charset="utf-8" />
        <style>
          body { font-family: -apple-system, Roboto, 'Noto Sans Devanagari', sans-serif; padding: 32px; color: #111; }
          h1 { font-size: 22px; margin-bottom: 4px; }
          .subtitle { color: #666; font-size: 13px; margin-bottom: 24px; }
          table { width: 100%; border-collapse: collapse; }
          td { padding: 10px 8px; border-bottom: 1px solid #ddd; vertical-align: top; }
          .label { width: 40%; font-weight: 600; color: #333; }
          .value { width: 60%; }
          .footer { margin-top: 32px; font-size: 11px; color: #999; }
        </style>
      </head>
      <body>
        <h1>${escapeHtml(schema.title)}</h1>
        <div class="subtitle">Filled with VaaniForm on ${printedOn}</div>
        <table>${rows}</table>
        <div class="footer">Generated by VaaniForm — a voice-first form filling assistant.</div>
      </body>
    </html>`;
}
